# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cooking-by-the-Book' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cooking-by-the-Book

  pod 'Parse'
  pod 'AlamofireImage'

end
